# Generated by Django 2.2 on 2020-07-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200712_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='tittle',
            new_name='title',
        ),
    ]
